// AUTH and USERS
export const SET_LOADING = "SET_LOADING";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGOUT = "LOGOUT";
export const AUTH_ERROR = "AUTH_ERROR";

export const USER_LOADED = "USER_LOADED";
export const USER_UPDATE = "USER_UPDATE";
export const USER_THEME_UPDATE = "USER_THEME_UPDATE";
export const USER_AVATAR_UPDATE = "USER_AVATAR_UPDATE";

export const ADD_FRIEND = "ADD_FRIEND";
export const REMOVE_FRIEND = "REMOVE_FRIEND";

export const REMOVE_FRIEND_REQUEST_NOTIFICATIONS =
  "REMOVE_FRIEND_REQUEST_NOTIFICATIONS";

export const REMOVE_LIKE_NOTIFICATION = "REMOVE_LIKE_NOTIFICATION";

// ALERTS
export const SET_ALERT = "SET_ALERT";
export const SET_MULTIPLE_ALERT = "SET_MULTIPLE_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REMOVE_ALL_ALERTS = "REMOVE_ALL_ALERTS";

export const SET_NOTIFICATIONS = "SET_NOTIFICATIONS";
